"""Initial Migration

Revision ID: a000276f9f8f
Revises: 6f5b8f7d4892
Create Date: 2021-08-27 19:34:21.736725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a000276f9f8f'
down_revision = '6f5b8f7d4892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
